# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10

  - name: Academic Affiliations
    url: '#experience'
    weight: 15  

  - name: Journal Articles
    url: '#publications'
    weight: 20   

  #- name: Book chapters
  #  url: '#bookchap'
  #  weight: 25   
    
  - name: Work in progress
    url: '#wpapers'
    weight: 30   

  #- name: Mimeos
  #  url: '#mimeo'
  #  weight: 35   

 # - name: Posts
 #   url: '#posts'
 #   weight: 20
  - name: Projects
    url: '#projects'
    weight: 40
 # - name: Talks
 #   url: '#talks'
 #   weight: 45
# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
  - name: Teaching
    url: '#teaching' #teaching
    weight: 50  
    
  - name: CV
    url: uploads/resume.pdf
    weight: 60

  - name: Experiments in Athens
    url: experimentsathens
    weight: 65

  - name: Link and resources
    url: linksresources
    weight: 70

  - name: Για φοιτητές
    url: forstudents
    weight: 80

  - name: Contact
    url: '#contact'
    weight: 55


